---
- name: ArgoCD | Create helm chart directory
  file:
    path: "{{ kube_config_dir }}/charts/argocd"
    state: directory
    owner: root
    group: root
    mode: 0755
  when:
    - inventory_hostname == groups['kube_control_plane'][0]

- name: ArgoCD | Copy Helm files
  copy:
    src: files/charts/argocd/
    dest: "{{ kube_config_dir }}/charts/argocd"
    owner: root
    group: root
    mode: 0644
  when:
    - inventory_hostname == groups['kube_control_plane'][0]


- name: ArgoCD | Helm install (upgrade)
  kubernetes.core.helm:
    name: argocd-configuration
    namespace: "{{ argocd_namespace }}"
    chart_ref: "{{ kube_config_dir }}/charts/argocd"
    values_files:
      - "{{ kube_config_dir }}/charts/argocd/values.yaml"
  when:
    - inventory_hostname == groups['kube_control_plane'][0]
