---
- name: ArgoCD Applications | Create addon dir
  file:
    path: "{{ kube_config_dir }}/addons/argocd_applications_install"
    state: directory
    owner: root
    group: root
    mode: 0755
  when:
    - inventory_hostname == groups['kube_control_plane'][0]

- name: ArgoCD Applications | Templates list
  set_fact:
    argocd_applicationset_install_templates:
      - { name: argocd-apps-namespace, file: argocd-apps-namespace.yml, type: ns }
      - { name: argocd-apps, file: argocd-applications.yml, type: deployment }             

- name: ArgoCD Applications | Create manifests
  template:
    src: "{{ item.file }}.j2"
    dest: "{{ kube_config_dir }}/addons/argocd_applications_install/{{ item.file }}"
  with_items: "{{ argocd_applications_install_templates }}"
  register: argocd_applications_install_manifests
  when:
    - inventory_hostname == groups['kube_control_plane'][0]

- name: ArgoCD Applications | Apply manifests
  kube:
    name: "{{ item.item.name }}"
    namespace: "{{ argocd_applications_namespace }}"
    kubectl: "{{ bin_dir }}/kubectl"
    resource: "{{ item.item.type }}"
    filename: "{{ kube_config_dir }}/addons/argocd_applications_install/{{ item.item.file }}"
    state: "latest"
  with_items: "{{ argocd_applications_install_manifests.results }}"