---
- name: ArgoCD ApplicationSet | Create addon dir
  file:
    path: "{{ kube_config_dir }}/addons/argocd_applicationset_install"
    state: directory
    owner: root
    group: root
    mode: 0755
  when:
    - inventory_hostname == groups['kube_control_plane'][0]

- name: ArgoCD ApplicationSet | Templates list
  set_fact:
    argocd_applicationset_install_templates:
      - { name: argocd-appset-namespace, file: argocd-applicationset-namespace.yml, type: ns }
      - { name: argocd-appset-customresourcedefinition, file: argocd-applicationset-customresourcedefinition.yml, type: crd }
      - { name: argocd-appset-serviceaccount, file: argocd-applicationset-serviceaccount.yml, type: sa }
      - { name: argocd-appset-role, file: argocd-applicationset-role.yml, type: role }             
      - { name: argocd-appset-deployment, file: argocd-applicationset-deployment.yml, type: deployment }        

- name: ArgoCD ApplicationSet | Create manifests
  template:
    src: "{{ item.file }}.j2"
    dest: "{{ kube_config_dir }}/addons/argocd_applicationset_install/{{ item.file }}"
  with_items: "{{ argocd_applicationset_install_templates }}"
  register: argocd_applicationset_install_manifests
  when:
    - inventory_hostname == groups['kube_control_plane'][0]

- name: ArgoCD ApplicationSet | Apply manifests
  kube:
    name: "{{ item.item.name }}"
    namespace: "{{ argocd_applicationset_namespace }}"
    kubectl: "{{ bin_dir }}/kubectl"
    resource: "{{ item.item.type }}"
    filename: "{{ kube_config_dir }}/addons/argocd_applicationset_install/{{ item.item.file }}"
    state: "latest"
  with_items: "{{ argocd_applicationset_install_manifests.results }}"